name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.DROPLET_PRIVATE_KEY}}
          
      - name: SSH into Droplet and update
        run: |
          ssh -o StrictHostKeyChecking=no -A root@64.227.166.179 "cd /var/www/dashApp_FE && git pull origin main"
